### ISSUE TITLE
Package doesn't work.

### ISSUE THREAD

**Issue by zinkq** [kennyhml/pyinterception#1]
Thanks for opening the issue in your repository!

I installed the interception driver correctly (I suppose) and also I have interception.dll file in the same folder as my code.
But I'm getting such an error when using your sample code:
`kdevice = interception.listen_to_keyboard()`
`AttributeError: module 'interception' has no attribute 'listen_to_keyboard'`

Also when I type `interception.` and look for any suggestions, there are none, though. 
It seems like the package doesn't work for me. Do you have any idea how to solve that?

**Comment by kennyhml** [comment]
Hey @zinkq, 

since the package is not (yet) available on pypi, I'd be curious to know how you downloaded it, because this simply sounds like a package manegement error on your side.

Ideally you would `git clone` the repository onto your computer, and then install the package as editable, or just put the folder into your site-packages yourself.

One more thing about interception, after you run the setup and reboot your computer, you do need to add the .dll to PATH as well.

Like I said I cant really help you here without more information of how you installed it and what the structure is like. `listen_to_keyboard` is definitely a valid function so long as you installed it correctly.
