### ISSUE TITLE
how to install properly?

### ISSUE THREAD

**Issue by wookidooki8** [kennyhml/pyinterception#10]
thought i had it work but no
1. i installed interception driver
2. added it to env path
3. i copy pasted src folder in the github and did this
 
        import interception

        kdevice = interception.listen_to_keyboard()
        mdevice = interception.listen_to_mouse() 

instead of getting two intergers i get listen event like below
![image](https://github.com/kennyhml/pyinterception/assets/104318789/d8e32649-2e24-4a2e-85e6-ae8490278863)

and when i click left button during mouse listen, every key and mouse button stop working.
what am i missing?.?

im using python 3.10 on windows10

**Comment by wookidooki8** [comment]
strangely i could just put 
interception.inputs.keyboard = 0
interception.inputs.mouse = 10

as it says im using keyboard device 0 and mouse decive 10 and it works but not sure if i have to go through the listen event everytime i use it

**Comment by Avnsx** [comment]
> Closed for inactivity & lack of information

This repository attracts all the kids from VAL0RANT now, their kernel anti-cheat flags interception driver or isolates the mouse / keyboard drivers, I'm not exactly sure, but that will exactly end up in what he's describing.

The reason they're hopping over to your repo is because val blocks the windows API, which means every python function that would allow them to control the mouse programmatically straight through python is gone and leaves them back with only two choices either try to intercept the HID drivers or use a arduino.

**Comment by kennyhml** [comment]
I thought it was already well known that vanguard detects the interception driver, 
I don't know how anyone could think that this wouldn't be the case lol...

I'll update the projects readme to clarify this at my nearest convenience.

Thank you for the input.

**Comment by Avnsx** [comment]
Btw @kennyhml I've never actually looked into the inner workings of interception driver, but would like to make use of inputs that do **not** get flagged for having the injected inputs ``LowLevelKeyHookInjected`` (0x10) flag.

But for the project I am working on a low performance consumption matters way more then, getting flagged or not.

So would you say that utilising interception driver together with your repository would be consuming drastically more CPU usage, then just calling functions like e.g. ``pyautogui.moveTo(x, y)`` which use the windows API? And by drastically I already mean for example 0,5% CPU usage more, or for example a constant stream of CPU usage due to even having to have the interception driver continously ran in the background, in first place. Or is that entirely not how interception driver works and it's more of a async process that just runs and does nothing at 0.00% CPU usage until it either gets called actively or a event happens

**Comment by kennyhml** [comment]
Well really what its mainly going to come down to whether you care about warping to x,y or whether you want to move there in a more human-like fashion (bezier-curve is a common way to do that). 

If youre just going to have it warp from a to b I would say that performance issues are going to be zero to none, what is expensive is moving it in a human fashion (since youre moving between lots of knots to get to the final destination).

Though on this again from my experience they are equally expensive and don't really impact the overall cpu usage much.

The driver does nothing while you're not using it by either capturing input events or sending them.
