### ISSUE TITLE
Rapid send() calls leads to dropped inputs and undefined behavior

### ISSUE THREAD

**Issue by WHalcyon** [kennyhml/pyinterception#35]
```
move_relative(10,0)
move_relative(10,0)
move_relative(10,0)
move_relative(-30,0)
```

I expect this to result in no change to cursor position, but it moves the cursor to the left. Sending multiple inputs quickly without sleeps in between causes erratic behavior, for example, continuously moving the cursor left 100 times then right 100 times in a loop will not only move the cursor erratically but also lock out manual inputs.

I don't know if this is caused by the input buffer being overwritten, the mouse's polling rate, some limitation in the interception driver, or python. Is this an issue in C++?

On a related note, it's probably not a good idea to filter mouse movements and re-send() them. Curious if you've ever encountered this issue.

**Comment by kennyhml** [comment]
Hi @WHalcyon,

this doesnt have anything to do with interception, python, or any input buffers being overwritten.
This is simply due to a feature called `Enhanced pointer precision` that is enabled by default. It helps make mouse movement feel more 'natural' for a real human and changes the behavior of the mouse.

You can disable this setting by opening your windows mouse settings -> additional mouse options -> Pointer options and from there you disable it. When you turn it off you will see the results you initially expected, but its gonna feel terrible to use your mouse manually. As far as Im aware this setting only affects relative mouse movements, not absolute mouse movements.

If you need high precision relative movements, I'm sure you can find a way to disable the pointer precision setting programmatically.

> On a related note, it's probably not a good idea to filter mouse movements and re-send() them

Why isnt that a good idea?

**Comment by WHalcyon** [comment]
Oh my god this does feel awful. It'll take a while to get used to.

Thank you. This has been causing me a ton of headaches and I've been using absolute coordinates because I assumed it was some kind of timing issue. I suspect this is going to resolve a ton of bugs I've had lol.

**Comment by kennyhml** [comment]
Update: It is possible to do it using `SystemParametersInfo` with `SPI_SETMOUSE`. Need to inquire whether that is an expensive opertion / whether the OS can properly handle the parameters swiftly changing - in which case we could just set the mouse acceleration to 0 before the relative movement.

Also, probably worth implementing the human movement using bezier curves using relative movements too as that is what it is natively when we capture our own mouse movements.

**Comment by WHalcyon** [comment]
As it turns out this issue was screwing with my debug but doesn't affect raw input, so the problem is sadly application specific. Definitely a useful setting to check though.

I believe relative/absolute mode is device dependent, though I've yet to find a mouse that uses absolute. Unless you're keen on your inputs blending in, I prefer using whichever mode suits the use case since relying on getcursorpos is a pain.

**Comment by kennyhml** [comment]
The functionality is added now, see [here](https://github.com/kennyhml/pyinterception/blob/eab1bbeaa9514355dcc890b9f4e502aac4e7aa1d/src/interception/_utils.py#L95).

Calls to `move_to` that use a bezier curve for human movement will automatically use relative movement now as well.
